Add missing limits header
Using clang 14 on Ubuntu the build fails with

```
vkutils.hpp:346:35: error: no member named 'numeric_limits' in namespace 'std'
                             std::numeric_limits<uint64_t>::max()) !=
```